using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace BdoGrindTracker.App.Capture;

/// <summary>
/// Calls the optional native HDR kernel once per image with borrowed pixel buffers.
/// The lookup is generated by the managed reference so both paths have identical rounding.
/// </summary>
internal static unsafe partial class NativeDesktopPixelConverter
{
    private const string LibraryName = "Grindcrest.Native.dll";
    private static readonly Lazy<bool> Available = new(CheckAvailability);
    private static int _disabled;

    internal static bool IsAvailable => Volatile.Read(ref _disabled) == 0 && Available.Value;

    internal static bool TryConvert(nint source, uint rowPitch, nint destination, int destinationStride,
        int width, int height, byte[] lookup)
    {
        if (source == 0 || destination == 0 || width <= 0 || height <= 0 ||
            (long)width * 8 > rowPitch || Math.Abs((long)destinationStride) < (long)width * 4 ||
            lookup is null || lookup.Length != 65536 || !IsAvailable)
            return false;

        fixed (byte* table = lookup)
        {
            try
            {
                return Convert(source, rowPitch, destination, destinationStride, width, height, table) == 0;
            }
            catch (Exception exception) when (IsUnavailable(exception))
            {
                // A missing/incompatible export must not stop capture or be retried every frame.
                Volatile.Write(ref _disabled, 1);
                Debug.WriteLine($"Native HDR conversion is unavailable: {exception.Message}");
                return false;
            }
        }
    }

    private static bool CheckAvailability()
    {
#if GRINDCREST_NATIVE_KERNELS
        if (!OperatingSystem.IsWindows() || RuntimeInformation.ProcessArchitecture != Architecture.X64)
            return false;
        try
        {
            return AbiVersion() == 1;
        }
        catch (Exception exception) when (IsUnavailable(exception))
        {
            Debug.WriteLine($"Native HDR conversion is unavailable: {exception.Message}");
            return false;
        }
#else
        // An explicit managed-only build also ignores DLLs left by an earlier native build.
        return false;
#endif
    }

    private static bool IsUnavailable(Exception exception) => exception is DllNotFoundException
        or EntryPointNotFoundException or BadImageFormatException;

    [LibraryImport(LibraryName, EntryPoint = "grindcrest_native_abi_version")]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    [DefaultDllImportSearchPaths(DllImportSearchPath.AssemblyDirectory)]
    private static partial int AbiVersion();

    [LibraryImport(LibraryName, EntryPoint = "grindcrest_convert_rgba16f_to_bgra8")]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    [DefaultDllImportSearchPaths(DllImportSearchPath.AssemblyDirectory)]
    private static partial int Convert(nint source, nuint sourceStride, nint destination,
        nint destinationStride, int width, int height, byte* lookup);
}
