<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\data\items.de.json" LogicalName="BdoGrindTracker.Core.GermanItems.json" WithCulture="false" />
    <EmbeddedResource Include="..\..\data\drop-quantities.json" LogicalName="BdoGrindTracker.Core.DropQuantities.json" />
  </ItemGroup>

</Project>
