// Reviewed public snapshot; regenerate with scripts/Import-ScreenshotSpots.py.
namespace BdoGrindTracker.Core;

public static partial class LootSpotCatalog
{
    private static LootSpot[] CreateScreenshotSpots() =>
    [
        new("gavinya-coastal-cliff", "Gavinya Coastal Cliff",
        [
            "Al Yurad's Ring Piece",
            "Ancient Spirit Dust",
            "Black Stone",
            "Caphras Stone",
            "Corrupt Oil of Immortality",
            "Crimson Primordial Luster - Sovereign",
            "Crimson Primordial Pigment - Sovereign",
            "Deboreka Belt",
            "Deboreka Earring",
            "Deboreka Necklace",
            "Deboreka Ring",
            "Empty Picture Frame",
            "Gavinya Coastal Cliff Paint",
            "Laila's Petal",
            "Pure Black Stone",
            "Refined Essence of Devouring",
            "Refined Origin of Hunger",
            "Sealed Black Magic Crystal",
            "Sulfur Golem Fragment",
            "Sulfur Golem Power Core",
            "Sulfur Golem Power Core Fragment",
            "Sunset Primordial Luster - Edana",
            "Sunset Primordial Pigment - Edana",
            "Turquoise Primordial Luster - Edana",
            "Turquoise Primordial Luster - Sovereign",
            "Turquoise Primordial Pigment - Edana",
            "Turquoise Primordial Pigment - Sovereign",
            "Violet Primordial Luster - Edana",
            "Violet Primordial Luster - Sovereign",
            "Violet Primordial Pigment - Edana",
            "Violet Primordial Pigment - Sovereign",
        ], "Sulfur Golem Fragment"),
        new("stars-end", "Star's End",
        [
            "Ancient Spirit Dust",
            "Black Distortion Earring",
            "Black Stone",
            "Caphras Stone",
            "Clear Blackstar Crystal",
            "Corrupted Gluttony Crystal",
            "Corrupted Sanguine Crystal",
            "Deboreka Earring",
            "Empty Picture Frame",
            "Gluttony Crystal",
            "Laila's Petal",
            "Origin of Corruption",
            "Pure Black Stone",
            "Sealed Black Magic Crystal",
        ], "Corrupted Sanguine Crystal"),
        new("sycraia-abyssal-ruins-lower", "Sycraia Abyssal Ruins (Lower)",
        [
            "Abyssal Essence",
            "Al Yurad's Ring Piece",
            "Ancient Spirit Dust",
            "Black Stone",
            "Caphras Stone",
            "Deboreka Ring",
            "Empty Picture Frame",
            "Faint Sycraia's Memory",
            "Gentle Sycraia's Memory",
            "Intense Sycraia's Memory",
            "Kehelle's Artifact - Black Spirit's Rage Max Increase",
            "Kehelle's Artifact - Max HP",
            "Kehelle's Artifact - Max Stamina",
            "Laila's Petal",
            "Lesha's Artifact - All Damage Reduction",
            "Lesha's Artifact - All Evasion",
            "Lesha's Artifact - Magic Damage Reduction",
            "Lesha's Artifact - Magic Evasion",
            "Lesha's Artifact - Melee Damage Reduction",
            "Lesha's Artifact - Melee Evasion",
            "Lesha's Artifact - Monster Damage Reduction",
            "Lesha's Artifact - Ranged Damage Reduction",
            "Lesha's Artifact - Ranged Evasion",
            "Marsh's Artifact - Extra AP Against Monsters",
            "Marsh's Artifact - Magic AP",
            "Marsh's Artifact - Magic Accuracy",
            "Marsh's Artifact - Melee AP",
            "Marsh's Artifact - Melee Accuracy",
            "Marsh's Artifact - Ranged AP",
            "Marsh's Artifact - Ranged Accuracy",
            "Pure Black Stone",
            "Radiant Sycraia's Memory",
            "Sealed Black Magic Crystal",
            "Sycraia Shard",
            "Sycraia Underwater Ruins Paint",
            "Traveler's Map",
            "Tungrad Ring",
            "Underwater Ancient Weapon Power Stone",
        ], "Underwater Ancient Weapon Power Stone"),
        new("elvia-orzekea", "[Elvia] Orzekea",
        [
            "Ancient Spirit Dust",
            "Black Stone",
            "Caphras Stone",
            "Deboreka Belt",
            "Deboreka Earring",
            "Empty Picture Frame",
            "Gem of Void",
            "Laila's Petal",
            "Pure Black Stone",
            "Sealed Black Magic Crystal",
            "Thorn-Entwined Weapon Fragment",
        ], "Thorn-Entwined Weapon Fragment"),
        new("dehkia-gyfin-rhasia-temple-upper", "[Dehkia] Gyfin Rhasia Temple (Upper)",
        [
            "Ancient Spirit Dust",
            "Black Stone",
            "Caphras Stone",
            "Crystal of Dogged Patience",
            "Crystal of Precise Destruction",
            "Crystal of Stalwart Fortitude",
            "Crystal of Unyielding Spirit",
            "Deboreka Belt",
            "Dehkia's Artifact - All Damage Reduction",
            "Dehkia's Artifact - All Evasion",
            "Dehkia's Fragment",
            "Destruction Spirit Stone",
            "Elkarr",
            "Empty Picture Frame",
            "Forest Fury",
            "Forgotten Limbo Box",
            "Guardian Spirit Stone",
            "Kehelle's Artifact - Black Spirit's Rage Max Increase",
            "Kehelle's Artifact - Max HP",
            "Kehelle's Artifact - Max Stamina",
            "Krogdalo's Origin Stone",
            "Laila's Petal",
            "Lesha's Artifact - All Damage Reduction",
            "Lesha's Artifact - All Evasion",
            "Lesha's Artifact - Magic Damage Reduction",
            "Lesha's Artifact - Magic Evasion",
            "Lesha's Artifact - Melee Damage Reduction",
            "Lesha's Artifact - Melee Evasion",
            "Lesha's Artifact - Monster Damage Reduction",
            "Lesha's Artifact - Ranged Damage Reduction",
            "Lesha's Artifact - Ranged Evasion",
            "Life Spirit Stone",
            "Manshaum Voodoo Doll",
            "Marsh's Artifact - Extra AP Against Monsters",
            "Marsh's Artifact - Magic AP",
            "Marsh's Artifact - Magic Accuracy",
            "Marsh's Artifact - Melee AP",
            "Marsh's Artifact - Melee Accuracy",
            "Marsh's Artifact - Ranged AP",
            "Marsh's Artifact - Ranged Accuracy",
            "Pure Black Stone",
            "Rumbling Earth Shard",
            "Swaying Wind Shard",
            "Tainted Bronze Fragment",
            "Trace of Nature",
            "Tungrad Belt",
            "Void Tainted Whispers",
        ], "Tainted Bronze Fragment"),
        new("tungrad-ruins", "Tungrad Ruins",
        [
            "Ancient Magic Crystal of Nature - Giant",
            "Ancient Spirit Dust",
            "Black Stone",
            "Caphras Stone",
            "Embers of Resonance",
            "Empty Picture Frame",
            "Essence of Devouring",
            "Forgotten Limbo Box",
            "Imperfect Lightstone of Earth",
            "Imperfect Lightstone of Fire",
            "Imperfect Lightstone of Wind",
            "Kuadir Fragment",
            "Lafi Bedmountain's Upgraded Telescope Parts",
            "Laila's Petal",
            "Origin of Dark Hunger",
            "Pure Black Stone",
            "Sealed Black Magic Crystal",
            "Specter's Energy",
            "Trace of Nature",
            "Tungrad Ruins Fragment",
            "Tungrad Ruins Paint",
        ], "Tungrad Ruins Fragment"),
        new("darkseekers-retreat", "Darkseeker's Retreat",
        [
            "Ancient Spirit Dust",
            "Black Stone",
            "Caphras Stone",
            "Darkseekers' Retreat Paint",
            "Decayed Cloth",
            "Embers of Resonance",
            "Empty Picture Frame",
            "Essence of Devouring",
            "Flame of Resonance",
            "Forgotten Limbo Box",
            "Imperfect Lightstone of Earth",
            "Imperfect Lightstone of Fire",
            "Imperfect Lightstone of Wind",
            "Kabua's Artifact",
            "Kabua's Fragment",
            "Lafi Bedmountain's Upgraded Telescope Parts",
            "Laila's Petal",
            "Origin of Dark Hunger",
            "Pure Black Stone",
            "Sealed Black Magic Crystal",
            "Trace of Nature",
        ], "Decayed Cloth"),
        new("fortunate-golden-pig-cave", "Fortunate Golden Pig Cave",
        [
            "Ancient Spirit Dust",
            "BON Dawn Crystal - Accuracy",
            "BON Dawn Crystal - All AP",
            "BON Dawn Crystal - Black Spirit's Rage",
            "BON Dawn Crystal - Damage Reduction",
            "BON Dawn Crystal - Evasion",
            "Black Stone",
            "Caphras Stone",
            "Empty Picture Frame",
            "Fortunate Golden Pig King Summon Scroll",
            "Fortunate Golden Pig King's Treasure Chest",
            "Golden Pigs Subjugation Token",
            "Laila's Petal",
            "Pure Black Stone",
            "Rare Treasure Chest",
            "Rare Treasures",
            "Shiny Treasure",
            "WON Dawn Crystal - Accuracy",
            "WON Dawn Crystal - All AP",
            "WON Dawn Crystal - Black Spirit's Rage",
            "WON Dawn Crystal - Damage Reduction",
            "WON Dawn Crystal - Evasion",
        ], "Shiny Treasure"),
        new("dehkia-mirumok-ruins", "[Dehkia] Mirumok Ruins",
        [
            "Ancient Spirit Dust",
            "Black Stone",
            "Caphras Stone",
            "Crystal of Dogged Patience",
            "Crystal of Precise Destruction",
            "Crystal of Stalwart Fortitude",
            "Crystal of Unyielding Spirit",
            "Deboreka Belt",
            "Dehkia's Artifact - All Damage Reduction",
            "Dehkia's Artifact - All Evasion",
            "Dehkia's Fragment",
            "Destruction Spirit Stone",
            "Elkarr",
            "Empty Picture Frame",
            "Forest Fury",
            "Forgotten Limbo Box",
            "Guardian Spirit Stone",
            "Kehelle's Artifact - Black Spirit's Rage Max Increase",
            "Kehelle's Artifact - Max HP",
            "Kehelle's Artifact - Max Stamina",
            "Krogdalo's Origin Stone",
            "Laila's Petal",
            "Lesha's Artifact - All Damage Reduction",
            "Lesha's Artifact - All Evasion",
            "Lesha's Artifact - Magic Damage Reduction",
            "Lesha's Artifact - Magic Evasion",
            "Lesha's Artifact - Melee Damage Reduction",
            "Lesha's Artifact - Melee Evasion",
            "Lesha's Artifact - Monster Damage Reduction",
            "Lesha's Artifact - Ranged Damage Reduction",
            "Lesha's Artifact - Ranged Evasion",
            "Life Spirit Stone",
            "Marsh's Artifact - Extra AP Against Monsters",
            "Marsh's Artifact - Magic AP",
            "Marsh's Artifact - Magic Accuracy",
            "Marsh's Artifact - Melee AP",
            "Marsh's Artifact - Melee Accuracy",
            "Marsh's Artifact - Ranged AP",
            "Marsh's Artifact - Ranged Accuracy",
            "Pure Black Stone",
            "Rumbling Earth Shard",
            "Swaying Wind Shard",
            "Tainted Wood Fragment",
            "Trace of Nature",
            "Valtarra Eclipsed Belt",
            "Void Tainted Whispers",
        ], "Tainted Wood Fragment"),
        new("winter-tree-fossil-280", "Winter Tree Fossil (280ap)",
        [
            "Ancient Magic Crystal of Nature - Adamantine",
            "Ancient Magic Crystal of Nature - Fighting Spirit",
            "Ancient Magic Crystal of Nature - Giant",
            "Ancient Spirit Dust",
            "Black Stone",
            "Caphras Stone",
            "Dragon Scale Fossil",
            "Empty Picture Frame",
            "Essence of Insight",
            "Forgotten Witch's Token",
            "Imperfect Lightstone of Earth",
            "Imperfect Lightstone of Fire",
            "Imperfect Lightstone of Wind",
            "Iridescent Lightstone",
            "Kehelle's Artifact - Black Spirit's Rage Max Increase",
            "Kehelle's Artifact - Max HP",
            "Kehelle's Artifact - Max Stamina",
            "Laila's Petal",
            "Lesha's Artifact - All Damage Reduction",
            "Lesha's Artifact - All Evasion",
            "Lesha's Artifact - Magic Damage Reduction",
            "Lesha's Artifact - Magic Evasion",
            "Lesha's Artifact - Melee Damage Reduction",
            "Lesha's Artifact - Melee Evasion",
            "Lesha's Artifact - Monster Damage Reduction",
            "Lesha's Artifact - Ranged Damage Reduction",
            "Lesha's Artifact - Ranged Evasion",
            "Magic Crystal of Infinity - Max HP",
            "Marsh's Artifact - Extra AP Against Monsters",
            "Marsh's Artifact - Magic AP",
            "Marsh's Artifact - Magic Accuracy",
            "Marsh's Artifact - Melee AP",
            "Marsh's Artifact - Melee Accuracy",
            "Marsh's Artifact - Ranged AP",
            "Marsh's Artifact - Ranged Accuracy",
            "Pure Black Stone",
            "Starlit Jade's Breath",
            "Winter Tree Snow Crystal",
        ], "Winter Tree Snow Crystal"),
        new("unlucky-golden-pig-cave", "Unlucky Golden Pig Cave",
        [
            "Ancient Spirit Dust",
            "BON Dawn Crystal - All AP",
            "Black Stone",
            "Caphras Stone",
            "Empty Picture Frame",
            "Essence of Dawn",
            "Faint Origin of Dark Hunger",
            "Fortunate Golden Pig King Summon Scroll",
            "Laila's Petal",
            "Pure Black Stone",
            "Shattered Treasures",
            "WON Dawn Crystal - All AP",
        ], "Shattered Treasures"),
        new("dehkia-ii-ash-forest", "[Dehkia II] Ash Forest",
        [
            "Al Yurad's Ring Piece",
            "Ancient Spirit Dust",
            "Ash Forest Paint",
            "Black Stone",
            "Caphras Stone",
            "Crystal of Dogged Patience",
            "Crystal of Precise Destruction",
            "Crystal of Stalwart Fortitude",
            "Crystal of Unyielding Spirit",
            "Deboreka Necklace",
            "Dehkia's Artifact - All Damage Reduction",
            "Dehkia's Artifact - All Evasion",
            "Dehkia's Fragment",
            "Empty Picture Frame",
            "Forgotten Limbo Box",
            "Laila's Petal",
            "Manshaum Voodoo Doll",
            "Pure Black Stone",
            "Quturan's Black Leaf",
            "Quturan's Left Lung",
            "Tainted Specter's Cloth",
            "Void Tainted Whispers",
        ], "Tainted Specter's Cloth"),
        new("dehkia-ii-oluns-valley", "[Dehkia II] Olun's Valley",
        [
            "Al Yurad's Ring Piece",
            "Ancient Spirit Dust",
            "Black Stone",
            "Caphras Stone",
            "Crystal of Dogged Patience",
            "Crystal of Precise Destruction",
            "Crystal of Stalwart Fortitude",
            "Crystal of Unyielding Spirit",
            "Deboreka Earring",
            "Dehkia's Artifact - All Damage Reduction",
            "Dehkia's Artifact - All Evasion",
            "Dehkia's Fragment",
            "Empty Picture Frame",
            "Forgotten Limbo Box",
            "Imperfect Lightstone of Earth",
            "Imperfect Lightstone of Fire",
            "Imperfect Lightstone of Wind",
            "Laila's Petal",
            "Olun's Valley Paint",
            "Pure Black Stone",
            "Quturan's Ashen Leaf",
            "Quturan's Right Lung",
            "Tainted Golem's Heart Fragment",
            "Void Tainted Whispers",
        ], "Tainted Golem's Heart Fragment"),
        new("yzrahid-highlands", "Yzrahid Highlands",
        [
            "Ancient Spirit Dust",
            "Black Stone",
            "Caphras Stone",
            "Corrupt Power Source",
            "Embers of Resonance",
            "Empty Picture Frame",
            "Flame of Resonance",
            "Forgotten Limbo Box",
            "Imperfect Lightstone of Earth",
            "Imperfect Lightstone of Fire",
            "Imperfect Lightstone of Wind",
            "Kabua's Artifact",
            "Kabua's Fragment",
            "Laila's Petal",
            "Pure Black Stone",
            "Sealed Black Magic Crystal",
            "Trace of Nature",
        ], "Corrupt Power Source"),
        new("elvia-hexe-sanctuary", "Hexe Sanctuary",
        [
            "Ancient Spirit Dust",
            "Ancient Spirit Light",
            "Black Distortion Earring",
            "Black Stone",
            "Blessed Soul Fragment",
            "Caphras Stone",
            "Corrupted Breath",
            "Crystallized Despair",
            "Empty Picture Frame",
            "Howling Bone Fragment",
            "Laila's Petal",
            "Mass of Pure Magic",
            "Pure Black Stone",
            "Sealed Black Magic Crystal",
            "Tattered Shadow",
            "Trace of Nature",
        ], "Howling Bone Fragment"),
        new("elvia-quint-hill", "Quint Hill",
        [
            "Ancient Spirit Dust",
            "Ancient Spirit Light",
            "Black Distortion Earring",
            "Black Stone",
            "Blessed Soul Fragment",
            "Caphras Stone",
            "Corrupted Breath",
            "Crystallized Despair",
            "Empty Picture Frame",
            "Fiery Troll Hide",
            "Forgotten Limbo Box",
            "Laila's Petal",
            "Mass of Pure Magic",
            "Pure Black Stone",
            "Sealed Black Magic Crystal",
            "Tattered Shadow",
            "Trace of Nature",
        ], "Fiery Troll Hide"),
        new("dokkebi-forest", "Dokkebi Forest",
        [
            "Ancient Spirit Dust",
            "BON Dawn Crystal - Accuracy",
            "BON Dawn Crystal - All AP",
            "BON Dawn Crystal - Black Spirit's Rage",
            "BON Dawn Crystal - Damage Reduction",
            "BON Dawn Crystal - Evasion",
            "Black Stone",
            "Caphras Stone",
            "Discarded Kkebicap",
            "Empty Picture Frame",
            "Laila's Petal",
            "Pure Black Stone",
            "WON Dawn Crystal - Accuracy",
            "WON Dawn Crystal - All AP",
            "WON Dawn Crystal - Black Spirit's Rage",
            "WON Dawn Crystal - Damage Reduction",
            "WON Dawn Crystal - Evasion",
        ], "Discarded Kkebicap"),
        new("dehkia-thornwood-forest", "[Dehkia] Thornwood Forest",
        [
            "Ah'krad",
            "Ancient Spirit Dust",
            "Black Stone",
            "Caphras Stone",
            "Dehkia's Fragment",
            "Empty Picture Frame",
            "Forgotten Limbo Box",
            "Imperfect Lightstone of Earth",
            "Imperfect Lightstone of Fire",
            "Imperfect Lightstone of Wind",
            "Kehelle's Artifact - Black Spirit's Rage Max Increase",
            "Kehelle's Artifact - Max HP",
            "Kehelle's Artifact - Max Stamina",
            "Laila's Petal",
            "Lesha's Artifact - All Damage Reduction",
            "Lesha's Artifact - All Evasion",
            "Lesha's Artifact - Magic Damage Reduction",
            "Lesha's Artifact - Magic Evasion",
            "Lesha's Artifact - Melee Damage Reduction",
            "Lesha's Artifact - Melee Evasion",
            "Lesha's Artifact - Monster Damage Reduction",
            "Lesha's Artifact - Ranged Damage Reduction",
            "Lesha's Artifact - Ranged Evasion",
            "Marsh's Artifact - Extra AP Against Monsters",
            "Marsh's Artifact - Magic AP",
            "Marsh's Artifact - Magic Accuracy",
            "Marsh's Artifact - Melee AP",
            "Marsh's Artifact - Melee Accuracy",
            "Marsh's Artifact - Ranged AP",
            "Marsh's Artifact - Ranged Accuracy",
            "Mass of Pure Magic",
            "Moonlight Spirit Powder",
            "Ominous Ring",
            "Pure Black Stone",
            "Quturan's Black Leaf",
            "Quturan's Left Lung",
            "Sealed Black Magic Crystal",
            "Silver",
            "Specter's Energy",
            "Tainted Moonlight Spirit Powder",
            "Venomous Night Fang",
            "Void Tainted Whispers",
        ], "Tainted Moonlight Spirit Powder"),
        new("city-of-the-dead", "City of the Dead",
        [
            "Ancient Magic Crystal of Nature - Giant",
            "Ancient Spirit Dust",
            "Black Stone",
            "Caphras Stone",
            "City of the Dead Paint",
            "Embers of Resonance",
            "Empty Picture Frame",
            "Essence of Devouring",
            "Forgotten Limbo Box",
            "Imperfect Lightstone of Earth",
            "Imperfect Lightstone of Fire",
            "Imperfect Lightstone of Wind",
            "Kabua's Artifact",
            "Kabua's Fragment",
            "Kuadir Fragment",
            "Lafi Bedmountain's Upgraded Telescope Parts",
            "Laila's Petal",
            "Mark of the Black Sands",
            "Origin of Dark Hunger",
            "Pure Black Stone",
            "Sealed Black Magic Crystal",
            "Specter's Energy",
            "Trace of Nature",
        ], "Mark of the Black Sands"),
        new("dehkia-cadry-ruins", "[Dehkia] Cadry Ruins",
        [
            "Ancient Spirit Dust",
            "Black Stone",
            "Caphras Stone",
            "Deboreka Ring",
            "Dehkia's Fragment",
            "Empty Picture Frame",
            "Forgotten Limbo Box",
            "Kehelle's Artifact - Black Spirit's Rage Max Increase",
            "Kehelle's Artifact - Max HP",
            "Kehelle's Artifact - Max Stamina",
            "Laila's Petal",
            "Lesha's Artifact - All Damage Reduction",
            "Lesha's Artifact - All Evasion",
            "Lesha's Artifact - Magic Damage Reduction",
            "Lesha's Artifact - Magic Evasion",
            "Lesha's Artifact - Melee Damage Reduction",
            "Lesha's Artifact - Melee Evasion",
            "Lesha's Artifact - Monster Damage Reduction",
            "Lesha's Artifact - Ranged Damage Reduction",
            "Lesha's Artifact - Ranged Evasion",
            "Marsh's Artifact - Extra AP Against Monsters",
            "Marsh's Artifact - Magic AP",
            "Marsh's Artifact - Magic Accuracy",
            "Marsh's Artifact - Melee AP",
            "Marsh's Artifact - Melee Accuracy",
            "Marsh's Artifact - Ranged AP",
            "Marsh's Artifact - Ranged Accuracy",
            "Pure Black Stone",
            "Ring of Cadry Guardian",
            "Scroll Written in Ancient Language",
            "Sealed Black Magic Crystal",
            "Tainted Cadry's Token",
            "Void Tainted Whispers",
        ], "Tainted Cadry's Token"),
        new("dehkia-ash-forest", "[Dehkia] Ash Forest",
        [
            "Al Yurad's Ring Piece",
            "Ancient Spirit Dust",
            "Ash Forest Paint",
            "Black Stone",
            "Caphras Stone",
            "Deboreka Necklace",
            "Dehkia's Fragment",
            "Empty Picture Frame",
            "Forgotten Limbo Box",
            "Imperfect Lightstone of Earth",
            "Imperfect Lightstone of Fire",
            "Imperfect Lightstone of Wind",
            "Kehelle's Artifact - Black Spirit's Rage Max Increase",
            "Kehelle's Artifact - Max HP",
            "Kehelle's Artifact - Max Stamina",
            "Laila's Petal",
            "Lesha's Artifact - All Damage Reduction",
            "Lesha's Artifact - All Evasion",
            "Lesha's Artifact - Magic Damage Reduction",
            "Lesha's Artifact - Magic Evasion",
            "Lesha's Artifact - Melee Damage Reduction",
            "Lesha's Artifact - Melee Evasion",
            "Lesha's Artifact - Monster Damage Reduction",
            "Lesha's Artifact - Ranged Damage Reduction",
            "Lesha's Artifact - Ranged Evasion",
            "Manshaum Voodoo Doll",
            "Marsh's Artifact - Extra AP Against Monsters",
            "Marsh's Artifact - Magic AP",
            "Marsh's Artifact - Magic Accuracy",
            "Marsh's Artifact - Melee AP",
            "Marsh's Artifact - Melee Accuracy",
            "Marsh's Artifact - Ranged AP",
            "Marsh's Artifact - Ranged Accuracy",
            "Mass of Pure Magic",
            "Pure Black Stone",
            "Quturan's Black Leaf",
            "Quturan's Left Lung",
            "Tainted Specter's Cloth",
            "Trace of Nature",
            "Void Tainted Whispers",
        ], "Tainted Specter's Cloth"),
        new("dehkia-crescent-shrine", "[Dehkia] Crescent Shrine",
        [
            "Ancient Spirit Dust",
            "Black Stone",
            "Caphras Stone",
            "Deboreka Ring",
            "Dehkia's Fragment",
            "Empty Picture Frame",
            "Forgotten Limbo Box",
            "Kehelle's Artifact - Black Spirit's Rage Max Increase",
            "Kehelle's Artifact - Max HP",
            "Kehelle's Artifact - Max Stamina",
            "Laila's Petal",
            "Lesha's Artifact - All Damage Reduction",
            "Lesha's Artifact - All Evasion",
            "Lesha's Artifact - Magic Damage Reduction",
            "Lesha's Artifact - Magic Evasion",
            "Lesha's Artifact - Melee Damage Reduction",
            "Lesha's Artifact - Melee Evasion",
            "Lesha's Artifact - Monster Damage Reduction",
            "Lesha's Artifact - Ranged Damage Reduction",
            "Lesha's Artifact - Ranged Evasion",
            "Marsh's Artifact - Extra AP Against Monsters",
            "Marsh's Artifact - Magic AP",
            "Marsh's Artifact - Magic Accuracy",
            "Marsh's Artifact - Melee AP",
            "Marsh's Artifact - Melee Accuracy",
            "Marsh's Artifact - Ranged AP",
            "Marsh's Artifact - Ranged Accuracy",
            "Pure Black Stone",
            "Ring of Crescent Guardian",
            "Scroll Written in Ancient Language",
            "Sealed Black Magic Crystal",
            "Tainted Token of Crescent",
            "Void Tainted Whispers",
        ], "Tainted Token of Crescent"),
        new("dehkia-cyclops-land", "[Dehkia] Cyclops Land",
        [
            "Ancient Magic Crystal - Addis",
            "Ancient Magic Crystal - Carmae",
            "Ancient Relic Crystal Shard",
            "Ancient Spirit Dust",
            "Black Stone",
            "Caphras Stone",
            "Corrupted Gargoyle Claw",
            "Dawn Earring",
            "Dehkia's Fragment",
            "Empty Picture Frame",
            "Forgotten Limbo Box",
            "Imperfect Lightstone of Earth",
            "Imperfect Lightstone of Fire",
            "Imperfect Lightstone of Wind",
            "Laila's Petal",
            "Pure Black Stone",
            "Sealed Black Magic Crystal",
            "Tainted Huge Spear",
            "Trace of Nature",
            "Void Tainted Whispers",
        ], "Tainted Huge Spear"),
        new("jade-starlight-forest", "Jade Starlight Forest",
        [
            "Ancient Spirit Dust",
            "Black Stone",
            "Caphras Stone",
            "Dragon Scale Fossil",
            "Embers of Frost",
            "Empty Picture Frame",
            "Essence of Insight",
            "Flame of Frost",
            "Forgotten Witch's Token",
            "Imperfect Lightstone of Earth",
            "Imperfect Lightstone of Fire",
            "Imperfect Lightstone of Wind",
            "Iridescent Lightstone",
            "Kehelle's Artifact - Black Spirit's Rage Max Increase",
            "Kehelle's Artifact - Max HP",
            "Kehelle's Artifact - Max Stamina",
            "Laila's Petal",
            "Lesha's Artifact - All Damage Reduction",
            "Lesha's Artifact - All Evasion",
            "Lesha's Artifact - Magic Damage Reduction",
            "Lesha's Artifact - Magic Evasion",
            "Lesha's Artifact - Melee Damage Reduction",
            "Lesha's Artifact - Melee Evasion",
            "Lesha's Artifact - Monster Damage Reduction",
            "Lesha's Artifact - Ranged Damage Reduction",
            "Lesha's Artifact - Ranged Evasion",
            "Marsh's Artifact - Extra AP Against Monsters",
            "Marsh's Artifact - Magic AP",
            "Marsh's Artifact - Magic Accuracy",
            "Marsh's Artifact - Melee AP",
            "Marsh's Artifact - Melee Accuracy",
            "Marsh's Artifact - Ranged AP",
            "Marsh's Artifact - Ranged Accuracy",
            "Ouk Pill of Time and Tide",
            "Pure Black Stone",
            "Starlit Jade Powder",
            "Starlit Jade's Breath",
        ], "Starlit Jade Powder"),
        new("dehkia-tunkuta", "[Dehkia] Tunkuta",
        [
            "Ancient Spirit Dust",
            "Black Stone",
            "Broken Horn Fragment",
            "Caphras Stone",
            "Dehkia's Fragment",
            "Embers of Despair",
            "Empty Picture Frame",
            "Flame of Despair",
            "Forgotten Limbo Box",
            "Imperfect Lightstone of Earth",
            "Imperfect Lightstone of Fire",
            "Imperfect Lightstone of Wind",
            "Kehelle's Artifact - Black Spirit's Rage Max Increase",
            "Kehelle's Artifact - Max HP",
            "Kehelle's Artifact - Max Stamina",
            "Laila's Petal",
            "Lesha's Artifact - All Damage Reduction",
            "Lesha's Artifact - All Evasion",
            "Lesha's Artifact - Magic Damage Reduction",
            "Lesha's Artifact - Magic Evasion",
            "Lesha's Artifact - Melee Damage Reduction",
            "Lesha's Artifact - Melee Evasion",
            "Lesha's Artifact - Monster Damage Reduction",
            "Lesha's Artifact - Ranged Damage Reduction",
            "Lesha's Artifact - Ranged Evasion",
            "Marsh's Artifact - Extra AP Against Monsters",
            "Marsh's Artifact - Magic AP",
            "Marsh's Artifact - Magic Accuracy",
            "Marsh's Artifact - Melee AP",
            "Marsh's Artifact - Melee Accuracy",
            "Marsh's Artifact - Ranged AP",
            "Marsh's Artifact - Ranged Accuracy",
            "Old Warrior's Horn Decoration",
            "Pure Black Stone",
            "Quturan's Ashen Leaf",
            "Quturan's Right Lung",
            "Sealed Black Magic Crystal",
            "Silver",
            "Tainted Broken Horn Fragment",
            "Thick Turo Blood",
            "Turo Heart",
            "Turo's Belt",
            "Venomous Night Fang",
            "Void Tainted Whispers",
        ], "Tainted Broken Horn Fragment"),
        new("dehkia-hystria-ruins", "[Dehkia] Hystria Ruins",
        [
            "Ancient Spirit Dust",
            "Black Stone",
            "Caphras Stone",
            "Deboreka Earring",
            "Dehkia's Fragment",
            "Empty Picture Frame",
            "Hystria Ruins Paint",
            "Imperfect Lightstone of Fire",
            "Kehelle's Artifact - Black Spirit's Rage Max Increase",
            "Kehelle's Artifact - Max HP",
            "Kehelle's Artifact - Max Stamina",
            "Lafi Bedmountain's Upgraded Compass Parts",
            "Laila's Petal",
            "Lesha's Artifact - All Damage Reduction",
            "Lesha's Artifact - All Evasion",
            "Lesha's Artifact - Magic Damage Reduction",
            "Lesha's Artifact - Magic Evasion",
            "Lesha's Artifact - Melee Damage Reduction",
            "Lesha's Artifact - Melee Evasion",
            "Lesha's Artifact - Monster Damage Reduction",
            "Lesha's Artifact - Ranged Damage Reduction",
            "Lesha's Artifact - Ranged Evasion",
            "Marsh's Artifact - Extra AP Against Monsters",
            "Marsh's Artifact - Magic AP",
            "Marsh's Artifact - Magic Accuracy",
            "Marsh's Artifact - Melee AP",
            "Marsh's Artifact - Melee Accuracy",
            "Marsh's Artifact - Ranged AP",
            "Marsh's Artifact - Ranged Accuracy",
            "Pure Black Stone",
            "Scroll Written in Ancient Language",
            "Sealed Black Magic Crystal",
            "Tainted Ruins Fragment",
            "Tungrad Earring",
            "Tungrad Necklace",
            "Void Tainted Whispers",
        ], "Tainted Ruins Fragment"),
        new("dark-energy-floodlands-great-red-sea", "(Great Red Sea) Dark Energy Floodlands",
        [
            "Ancient Spirit Dust",
            "Black Stone",
            "Caphras Stone",
            "Deboreka Belt",
            "Deboreka Earring",
            "Deboreka Necklace",
            "Deboreka Ring",
            "Empty Picture Frame",
            "Faded Dark Energy",
            "Flawless Herald's Crystal",
            "HAN Crystal of Dusky Ruin",
            "Laila's Petal",
            "Pure Black Stone",
            "Silent Crystal of Origin",
            "Tainted Armor Fragment",
        ], "Tainted Armor Fragment"),
        new("dark-energy-floodlands-orbita", "(Orbita) Dark Energy Floodlands",
        [
            "Ancient Spirit Dust",
            "Black Stone",
            "Caphras Stone",
            "Deboreka Belt",
            "Deboreka Earring",
            "Deboreka Necklace",
            "Deboreka Ring",
            "Empty Picture Frame",
            "Faded Dark Energy",
            "Flawless Herald's Crystal",
            "HAN Crystal of Dusky Ruin",
            "Laila's Petal",
            "Pure Black Stone",
            "Silent Crystal of Origin",
            "Tainted Armor Fragment",
        ], "Tainted Armor Fragment"),
        new("dark-energy-floodlands-zephyros", "(Zephyros) Dark Energy Floodlands",
        [
            "Ancient Spirit Dust",
            "Black Stone",
            "Caphras Stone",
            "Deboreka Belt",
            "Deboreka Earring",
            "Deboreka Necklace",
            "Deboreka Ring",
            "Empty Picture Frame",
            "Faded Dark Energy",
            "Flawless Herald's Crystal",
            "HAN Crystal of Dusky Ruin",
            "Laila's Petal",
            "Pure Black Stone",
            "Silent Crystal of Origin",
            "Tainted Armor Fragment",
        ], "Tainted Armor Fragment"),
        new("dehkia-ash-forest-unspecified", "[Dehkia] Ash Forest (Stufe wählen)",
        [
            "Al Yurad's Ring Piece",
            "Ancient Spirit Dust",
            "Ash Forest Paint",
            "Black Stone",
            "Caphras Stone",
            "Crystal of Dogged Patience",
            "Crystal of Precise Destruction",
            "Crystal of Stalwart Fortitude",
            "Crystal of Unyielding Spirit",
            "Deboreka Necklace",
            "Dehkia's Artifact - All Damage Reduction",
            "Dehkia's Artifact - All Evasion",
            "Dehkia's Fragment",
            "Empty Picture Frame",
            "Forgotten Limbo Box",
            "Imperfect Lightstone of Earth",
            "Imperfect Lightstone of Fire",
            "Imperfect Lightstone of Wind",
            "Kehelle's Artifact - Black Spirit's Rage Max Increase",
            "Kehelle's Artifact - Max HP",
            "Kehelle's Artifact - Max Stamina",
            "Laila's Petal",
            "Lesha's Artifact - All Damage Reduction",
            "Lesha's Artifact - All Evasion",
            "Lesha's Artifact - Magic Damage Reduction",
            "Lesha's Artifact - Magic Evasion",
            "Lesha's Artifact - Melee Damage Reduction",
            "Lesha's Artifact - Melee Evasion",
            "Lesha's Artifact - Monster Damage Reduction",
            "Lesha's Artifact - Ranged Damage Reduction",
            "Lesha's Artifact - Ranged Evasion",
            "Manshaum Voodoo Doll",
            "Marsh's Artifact - Extra AP Against Monsters",
            "Marsh's Artifact - Magic AP",
            "Marsh's Artifact - Magic Accuracy",
            "Marsh's Artifact - Melee AP",
            "Marsh's Artifact - Melee Accuracy",
            "Marsh's Artifact - Ranged AP",
            "Marsh's Artifact - Ranged Accuracy",
            "Mass of Pure Magic",
            "Pure Black Stone",
            "Quturan's Black Leaf",
            "Quturan's Left Lung",
            "Tainted Specter's Cloth",
            "Trace of Nature",
            "Void Tainted Whispers",
        ], "Tainted Specter's Cloth"),
        new("winter-tree-fossil-unspecified", "Winter Tree Fossil (AP bestätigen)",
        [
            "Ancient Magic Crystal of Nature - Adamantine",
            "Ancient Magic Crystal of Nature - Fighting Spirit",
            "Ancient Magic Crystal of Nature - Giant",
            "Ancient Spirit Dust",
            "Black Stone",
            "Caphras Stone",
            "Dragon Scale Fossil",
            "Empty Picture Frame",
            "Essence of Insight",
            "Forgotten Witch's Token",
            "Imperfect Lightstone of Earth",
            "Imperfect Lightstone of Fire",
            "Imperfect Lightstone of Wind",
            "Iridescent Lightstone",
            "Kehelle's Artifact - Black Spirit's Rage Max Increase",
            "Kehelle's Artifact - Max HP",
            "Kehelle's Artifact - Max Stamina",
            "Laila's Petal",
            "Lesha's Artifact - All Damage Reduction",
            "Lesha's Artifact - All Evasion",
            "Lesha's Artifact - Magic Damage Reduction",
            "Lesha's Artifact - Magic Evasion",
            "Lesha's Artifact - Melee Damage Reduction",
            "Lesha's Artifact - Melee Evasion",
            "Lesha's Artifact - Monster Damage Reduction",
            "Lesha's Artifact - Ranged Damage Reduction",
            "Lesha's Artifact - Ranged Evasion",
            "Magic Crystal of Infinity - Max HP",
            "Marsh's Artifact - Extra AP Against Monsters",
            "Marsh's Artifact - Magic AP",
            "Marsh's Artifact - Magic Accuracy",
            "Marsh's Artifact - Melee AP",
            "Marsh's Artifact - Melee Accuracy",
            "Marsh's Artifact - Ranged AP",
            "Marsh's Artifact - Ranged Accuracy",
            "Pure Black Stone",
            "Starlit Jade's Breath",
            "Winter Tree Snow Crystal",
        ], "Winter Tree Snow Crystal"),
    ];

    public static IReadOnlyList<LootSpot> VariantsFor(string spotId)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(spotId);
        string[] ids = spotId switch
        {
            "dark-energy-floodlands" or "dark-energy-floodlands-zephyros" or
                "dark-energy-floodlands-orbita" or "dark-energy-floodlands-great-red-sea" =>
                ["dark-energy-floodlands-zephyros", "dark-energy-floodlands-orbita", "dark-energy-floodlands-great-red-sea"],
            "dehkia-ash-forest-unspecified" or "dehkia-ash-forest" or "dehkia-ii-ash-forest" =>
                ["dehkia-ash-forest", "dehkia-ii-ash-forest"],
            "winter-tree-fossil-unspecified" or "winter-tree-fossil-280" => ["winter-tree-fossil-280"],
            _ => [spotId],
        };
        return Array.AsReadOnly(ids.Select(id => Spots.FirstOrDefault(spot => spot.Id == id))
            .OfType<LootSpot>().ToArray());
    }

    internal static string? DetectScreenshotSpot(string trashName)
    {
        if (trashName == "Tainted Specter's Cloth") return "dehkia-ash-forest-unspecified";
        if (trashName == "Winter Tree Snow Crystal") return "winter-tree-fossil-unspecified";
        var candidates = Spots.Where(spot => spot.PrimaryTrashItemName == trashName).Take(2).ToArray();
        return candidates.Length == 1 ? candidates[0].Id : null;
    }
}
