// Reviewed public snapshot; regenerate with scripts/Import-ScreenshotSpots.py.
namespace BdoGrindTracker.App.Pricing;

internal static partial class LootPriceCatalog
{
    private static LootPriceDefinition[] ScreenshotDefinitions() =>
    [
        Market("Abyssal Essence", 9774),
        new("Ah'krad", LootPriceKind.Unknown),
        Fixed("Al Yurad's Ring Piece", 0),
        Market("Ancient Magic Crystal - Addis", 15649),
        Market("Ancient Magic Crystal - Carmae", 15605),
        Market("Ancient Magic Crystal of Nature - Adamantine", 15616),
        Market("Ancient Magic Crystal of Nature - Fighting Spirit", 15712),
        Market("Ancient Magic Crystal of Nature - Giant", 15714),
        Market("Ancient Relic Crystal Shard", 40218),
        Fixed("Ancient Spirit Light", 0),
        Fixed("Ash Forest Paint", 0),
        Market("BON Dawn Crystal - Accuracy", 15268),
        Market("BON Dawn Crystal - All AP", 15262),
        Market("BON Dawn Crystal - Black Spirit's Rage", 15265),
        Market("BON Dawn Crystal - Damage Reduction", 15271),
        Market("BON Dawn Crystal - Evasion", 15274),
        Market("Black Distortion Earring", 11853),
        Market("Blessed Soul Fragment", 8421),
        Fixed("Broken Horn Fragment", 18000),
        Fixed("City of the Dead Paint", 0),
        new("Clear Blackstar Crystal", LootPriceKind.Unknown),
        Fixed("Corrupt Power Source", 25190),
        Market("Corrupted Breath", 8427),
        Fixed("Corrupted Gargoyle Claw", 16990),
        Market("Corrupted Gluttony Crystal", 15741),
        Fixed("Corrupted Sanguine Crystal", 155000),
        Market("Crystal of Dogged Patience", 15259),
        Market("Crystal of Precise Destruction", 15257),
        Market("Crystal of Stalwart Fortitude", 15258),
        Market("Crystal of Unyielding Spirit", 15260),
        Market("Crystallized Despair", 8411),
        Fixed("Darkseekers' Retreat Paint", 0),
        Market("Dawn Earring", 11855),
        Fixed("Decayed Cloth", 45570),
        Market("Dehkia's Artifact - All Damage Reduction", 748021),
        Market("Dehkia's Artifact - All Evasion", 748022),
        Market("Dehkia's Fragment", 767091),
        Market("Destruction Spirit Stone", 45298),
        Fixed("Discarded Kkebicap", 52571),
        Market("Dragon Scale Fossil", 44364),
        new("Elkarr", LootPriceKind.Unknown),
        Market("Embers of Despair", 44475),
        new("Embers of Frost", LootPriceKind.Unknown),
        Market("Embers of Resonance", 65318),
        Market("Essence of Dawn", 820979),
        Market("Essence of Devouring", 65323),
        Market("Essence of Insight", 9791),
        Market("Faint Origin of Dark Hunger", 767102),
        Fixed("Faint Sycraia's Memory", 150000000),
        Fixed("Fiery Troll Hide", 96750),
        Market("Flame of Despair", 44462),
        Market("Flame of Frost", 44497),
        Market("Flame of Resonance", 65317),
        Market("Forest Fury", 4917),
        new("Forgotten Limbo Box", LootPriceKind.Unknown),
        Fixed("Forgotten Witch's Token", 0),
        Fixed("Fortunate Golden Pig King Summon Scroll", 0),
        Fixed("Fortunate Golden Pig King's Treasure Chest", 0),
        Fixed("Gavinya Coastal Cliff Paint", 0),
        Market("Gem of Void", 821182),
        Fixed("Gentle Sycraia's Memory", 300000000),
        Market("Gluttony Crystal", 821344),
        Fixed("Golden Pigs Subjugation Token", 0),
        Market("Guardian Spirit Stone", 45300),
        Fixed("Howling Bone Fragment", 26190),
        Fixed("Hystria Ruins Paint", 0),
        Market("Imperfect Lightstone of Earth", 766105),
        Market("Imperfect Lightstone of Fire", 766104),
        Market("Imperfect Lightstone of Wind", 766106),
        Fixed("Intense Sycraia's Memory", 900000000),
        Market("Iridescent Lightstone", 766101),
        Market("Kabua's Artifact", 742269),
        Market("Kabua's Fragment", 59881),
        Fixed("Kehelle's Artifact - Black Spirit's Rage Max Increase", 20100000),
        Fixed("Kehelle's Artifact - Max HP", 20100000),
        Fixed("Kehelle's Artifact - Max Stamina", 20100000),
        Market("Krogdalo's Origin Stone", 50801),
        new("Kuadir Fragment", LootPriceKind.Unknown),
        new("Lafi Bedmountain's Upgraded Compass Parts", LootPriceKind.Unknown),
        Fixed("Lafi Bedmountain's Upgraded Telescope Parts", 0),
        Fixed("Lesha's Artifact - All Damage Reduction", 20100000),
        Fixed("Lesha's Artifact - All Evasion", 20100000),
        Fixed("Lesha's Artifact - Magic Damage Reduction", 20100000),
        Fixed("Lesha's Artifact - Magic Evasion", 20100000),
        Fixed("Lesha's Artifact - Melee Damage Reduction", 20100000),
        Fixed("Lesha's Artifact - Melee Evasion", 20100000),
        Fixed("Lesha's Artifact - Monster Damage Reduction", 20100000),
        Fixed("Lesha's Artifact - Ranged Damage Reduction", 20100000),
        Fixed("Lesha's Artifact - Ranged Evasion", 20100000),
        Market("Life Spirit Stone", 45302),
        Market("Magic Crystal of Infinity - Max HP", 15136),
        Market("Manshaum Voodoo Doll", 40383),
        Fixed("Mark of the Black Sands", 32900),
        Fixed("Marsh's Artifact - Extra AP Against Monsters", 20100000),
        Fixed("Marsh's Artifact - Magic AP", 20100000),
        Fixed("Marsh's Artifact - Magic Accuracy", 20100000),
        Fixed("Marsh's Artifact - Melee AP", 20100000),
        Fixed("Marsh's Artifact - Melee Accuracy", 20100000),
        Fixed("Marsh's Artifact - Ranged AP", 20100000),
        Fixed("Marsh's Artifact - Ranged Accuracy", 20100000),
        Fixed("Mass of Pure Magic", 51000),
        Fixed("Moonlight Spirit Powder", 15000),
        Fixed("Old Warrior's Horn Decoration", 12000),
        Fixed("Olun's Valley Paint", 0),
        Market("Ominous Ring", 12068),
        Fixed("Origin of Corruption", 3000000000),
        Market("Origin of Dark Hunger", 65319),
        Market("Ouk Pill of Time and Tide", 9070),
        Fixed("Quturan's Ashen Leaf", 0),
        Fixed("Quturan's Black Leaf", 0),
        Fixed("Quturan's Left Lung", 0),
        Fixed("Quturan's Right Lung", 0),
        Fixed("Radiant Sycraia's Memory", 3000000000),
        Fixed("Rare Treasure Chest", 0),
        Fixed("Rare Treasures", 0),
        Market("Ring of Cadry Guardian", 12032),
        Market("Ring of Crescent Guardian", 12031),
        Market("Rumbling Earth Shard", 50803),
        Market("Scroll Written in Ancient Language", 40228),
        Fixed("Shattered Treasures", 59415),
        Fixed("Shiny Treasure", 59415),
        Fixed("Silver", 1),
        Fixed("Specter's Energy", 30000000),
        Fixed("Starlit Jade Powder", 20140),
        Fixed("Starlit Jade's Breath", 100000),
        Fixed("Sulfur Golem Fragment", 165508),
        Market("Sulfur Golem Power Core", 980115),
        Market("Sulfur Golem Power Core Fragment", 980116),
        Market("Swaying Wind Shard", 50802),
        Market("Sycraia Shard", 821347),
        Fixed("Sycraia Underwater Ruins Paint", 0),
        Fixed("Tainted Broken Horn Fragment", 40000),
        Fixed("Tainted Bronze Fragment", 125900),
        Fixed("Tainted Cadry's Token", 35880),
        Fixed("Tainted Golem's Heart Fragment", 117700),
        Fixed("Tainted Huge Spear", 32950),
        Fixed("Tainted Moonlight Spirit Powder", 39000),
        Fixed("Tainted Ruins Fragment", 34270),
        Fixed("Tainted Specter's Cloth", 52500),
        Fixed("Tainted Token of Crescent", 38800),
        Fixed("Tainted Wood Fragment", 101500),
        Fixed("Tattered Shadow", 25207),
        Market("Thick Turo Blood", 9778),
        Fixed("Thorn-Entwined Weapon Fragment", 96040),
        Market("Trace of Nature", 5960),
        Market("Traveler's Map", 16017),
        Market("Tungrad Belt", 12237),
        Market("Tungrad Earring", 11828),
        Market("Tungrad Necklace", 11629),
        Market("Tungrad Ring", 12061),
        Fixed("Tungrad Ruins Fragment", 35100),
        Fixed("Tungrad Ruins Paint", 0),
        Market("Turo Heart", 44461),
        Market("Turo's Belt", 12257),
        Market("Turquoise Primordial Luster - Edana", 821418),
        Market("Turquoise Primordial Luster - Sovereign", 821417),
        Market("Turquoise Primordial Pigment - Edana", 767342),
        Market("Turquoise Primordial Pigment - Sovereign", 767341),
        Fixed("Underwater Ancient Weapon Power Stone", 107900),
        Market("Valtarra Eclipsed Belt", 12236),
        Fixed("Venomous Night Fang", 30000),
        Fixed("Void Tainted Whispers", 0),
        Market("WON Dawn Crystal - Accuracy", 15269),
        Market("WON Dawn Crystal - All AP", 15263),
        Market("WON Dawn Crystal - Black Spirit's Rage", 15266),
        Market("WON Dawn Crystal - Damage Reduction", 15272),
        Market("WON Dawn Crystal - Evasion", 15275),
        Fixed("Winter Tree Snow Crystal", 5620),
    ];
}
